In [0]:
import numpy as np

In [0]:
# Matriz
A = np.array([[2, -1],
              [0, 4]])

In [0]:
A

array([[ 2, -1],
       [ 0,  4]])

In [0]:
B = np.array([[1, 0, -4],
              [4, -3, 2]])

In [0]:
B

array([[ 1,  0, -4],
       [ 4, -3,  2]])

In [0]:
# Matriz segunda representação
F = np.matrix('1 2; 3 4')

In [0]:
?np.array

In [20]:
F.shape

(2, 2)

In [0]:
F

matrix([[1, 2],
        [3, 4]])

In [0]:
D = np.matrix([[2, -1],[0, 4]])

In [0]:
D

matrix([[ 2, -1],
        [ 0,  4]])

In [0]:
type(D)

numpy.matrix

In [0]:
#Matriz linha
L = np.array([3,4,5])

In [4]:
L

array([3, 4, 5])

In [0]:
L2 = np.array([[3,4,6]])

In [5]:
L.shape

(3,)

In [9]:
L2.shape

(1, 3)

In [0]:
#Matriz coluna
C1 = np.array([[1],[3],[7]])

In [12]:
C1

array([[1],
       [3],
       [7]])

In [13]:
C1.shape

(3, 1)

In [0]:
#Matriz nula
N = np.zeros([2,2])

In [0]:
?np.zeros

In [17]:
N

array([[0., 0.],
       [0., 0.]])